name: Adds all issues that include the 'tracked' label to WheelNext project board

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/wheelnext/projects/4
          github-token: ${{ secrets.CI_TOKEN }}
          labeled: tracked
